/**
 * types.ts — the storage boundary
 *
 * Everything above this interface deals in parsed, migrated, validated data and
 * knows nothing about GitHub. That is deliberate: the git-JSON-versus-database
 * question is still open, and this is the seam where that decision gets made
 * without rewriting the tools.
 *
 * Writes are expressed as mutations, not as put(data). A verb hands over a
 * function that changes one path; the adapter owns the read-modify-write cycle
 * and the conflict retry. Tools therefore never see a SHA, and — because a
 * retry re-runs the mutation against freshly read data — a concurrent change to
 * a different path survives instead of being clobbered. That property is the
 * whole reason scoped verbs were chosen over whole-file writes.
 */

import type { DataFileName, SliceData } from '../../../src/lib/schemas'

export interface ReadResult<K extends DataFileName> {
  data: SliceData<K>
  /** Opaque version marker — a git blob SHA today. Writes will need it. */
  sha: string
}

export interface StorageAdapter {
  /** Workspace directories available in the data repo. */
  listWorkspaces(): Promise<string[]>

  /** Read one data file, migrated to the current schema and structurally validated. */
  readFile<K extends DataFileName>(workspace: string, name: K): Promise<ReadResult<K>>

  /**
   * Read the file, apply `mutate` to it in place, and write it back.
   *
   * On a stale-SHA conflict the whole cycle runs again against fresh data, so
   * `mutate` must be safe to run more than once — keep it a pure function of
   * the data it is handed, with any randomness (IDs, timestamps) generated by
   * the caller beforehand and captured in the closure.
   */
  mutateFile<K extends DataFileName>(
    workspace: string,
    name: K,
    mutate: (data: SliceData<K>) => void,
    commitMessage: string,
  ): Promise<ReadResult<K>>
}

/** Thrown when a data file does not exist in the given workspace. */
export class NotFoundError extends Error {
  constructor(workspace: string, name: string) {
    super(`${name}.json does not exist in workspace "${workspace}".`)
    this.name = 'NotFoundError'
  }
}

/** Thrown when the remote moved underneath us and the retry also lost the race. */
export class ConflictError extends Error {
  constructor(workspace: string, name: string) {
    super(
      `${name}.json in "${workspace}" was modified concurrently and the retry also conflicted. ` +
      `Nothing was written. Try again.`,
    )
    this.name = 'ConflictError'
  }
}
